name: Receiver Pipe

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install dependencies
      run: |
         pip install flake8
         if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Software build for production
      run: g++ -Wall -Wextra -o bmsReceiver Bms_Receiver/*.c* | mvn compile exec:java -Dexec.mainClass="streambms.sender.BMSSenderService"
      
    - name: bmsReceiver production
      run: ./bmsReceiver
