name: Receiver Limit complexity

on: [push, pull_request]

jobs:
  complexcheck:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install lizard
      run: pip install lizard

    - name: Limit complexity
      run: $HOME/.local/bin/lizard Bms_Receiver/Receiver_DataCalc.c --CCN 3
